insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Moore', 'Utrecht', 179, '0280 ZC', 'Enschede', '42-84112523', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Green', 'Amsterdam', 125, '7977 MU', 'Zaandam', '34-77328725', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Lopez', 'The Hague', 217, '0262 IZ', 'Katwijk', '65-44920578', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Mitchell', 'Rotterdam', 106, '5183 TP', 'Nijmegen', '88-10222671', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Turner', 'Eindhoven', 242, '9856 MB', 'Schiedam', '54-95420371', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Nelson', 'Rotterdam', 114, '6603 CW', 'Maastricht', '20-39990654', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Hall', 'Amsterdam', 124, '8281 SW', 'Heerlen', '53-76423004', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Flores', 'Eindhoven', 216, '3773 TO', 'Dordrecht', '92-98240544', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Wilson', 'Eindhoven', 213, '8809 TV', 'Vlaardingen', '36-34279577', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Washington', 'Rotterdam', 25, '7594 ZU', 'Hoorn', '45-22259390', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Mitchell', 'Rotterdam', 119, '4822 XO', 'Breda', '32-40027516', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Washington', 'The Hague', 117, '4193 WM', 'Leiden', '14-52435285', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Cox', 'Rotterdam', 146, '2667 EH', 'Apeldoorn', '89-36453802', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Gray', 'Rotterdam', 213, '0881 YV', 'Zaanstad', '19-61615922', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Patterson', 'Amsterdam', 155, '9361 KE', 'Eindhoven', '92-87990281', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Jackson', 'Eindhoven', 110, '3297 JV', 'Hengelo', '14-74564379', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Price', 'Utrecht', 207, '4608 FQ', 'Schiedam', '67-88149001', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'Allen', 'Eindhoven', 202, '1367 CM', 'Hilversum', '27-89431181', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Parker', 'Amsterdam', 19, '7296 TH', 'Zeist', '45-56218139', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Charlotte', 'Gonzalez', 'Eindhoven', 1, '5635 MY', 'Haarlem', '73-28919026', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Mitchell', 'The Hague', 254, '9541 YT', 'Assen', '36-53159501', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Richardson', 'Utrecht', 43, '9982 WE', 'Leeuwarden', '11-84032573', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Washington', 'Utrecht', 143, '2278 TN', 'Katwijk', '70-57811472', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Hill', 'Amsterdam', 46, '6675 MQ', 'Gouda', '85-25122410', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Wright', 'Amsterdam', 148, '7152 KZ', 'Groningen', '53-19894379', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Hall', 'Amsterdam', 254, '9087 IT', 'Tilburg', '51-98984926', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Wood', 'Utrecht', 45, '0411 PW', 'Roosendaal', '33-49096721', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Sanchez', 'Amsterdam', 107, '6700 MB', 'Dordrecht', '31-50462917', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Butler', 'Utrecht', 199, '7379 LA', 'Leeuwarden', '24-02368389', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Cox', 'Eindhoven', 214, '5265 NT', 'Purmerend', '66-35466110', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Bailey', 'Amsterdam', 178, '5930 AC', 'Purmerend', '61-29592656', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Campbell', 'Amsterdam', 247, '6825 KU', 'Assen', '58-47410937', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Kelly', 'The Hague', 212, '7615 FK', 'Amsterdam', '58-11518215', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Martin', 'Rotterdam', 86, '7559 SG', 'Leiden', '10-46900494', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Baker', 'Utrecht', 181, '6967 KB', 'Leeuwarden', '38-54777818', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Robinson', 'Eindhoven', 205, '7244 IC', 'Veenendaal', '26-03331223', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Brown', 'Rotterdam', 4, '7951 TS', 'Enschede', '31-87426994', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Price', 'Eindhoven', 229, '8001 GR', 'Amersfoort', '73-54587220', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Taylor', 'Utrecht', 96, '5583 WM', 'Breda', '67-61831783', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kinsley', 'Ramirez', 'Utrecht', 69, '1777 CW', 'Veenendaal', '13-58673370', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Barnes', 'Rotterdam', 172, '0545 QO', 'Deventer', '44-74750157', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'Robinson', 'Amsterdam', 133, '5206 DU', 'Gouda', '52-63384832', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Jackson', 'Rotterdam', 244, '7897 AE', 'Delft', '32-39180760', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Miller', 'Eindhoven', 12, '8798 SV', 'Haarlem', '29-16738955', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'White', 'Utrecht', 33, '2025 ZY', 'Gouda', '70-73807188', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Long', 'Eindhoven', 222, '5783 FJ', 'Hengelo', '50-64831713', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Bennett', 'Rotterdam', 204, '7373 MB', 'Utrecht', '28-42055347', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Bennett', 'Eindhoven', 222, '7667 OK', 'Katwijk', '44-05021024', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'Jenkins', 'Amsterdam', 173, '5011 TR', 'Den Haag', '00-82034551', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Jackson', 'Utrecht', 123, '5855 SY', 'Amersfoort', '17-62022301', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Powell', 'Rotterdam', 17, '2239 YF', 'Veenendaal', '08-75619779', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isla', 'Simmons', 'Amsterdam', 33, '2149 AM', 'Breda', '63-52396671', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Richardson', 'Utrecht', 12, '1420 BA', 'Amsterdam', '22-81323511', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Lopez', 'Amsterdam', 53, '7980 WL', 'Enschede', '37-35192301', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Powell', 'Amsterdam', 151, '3215 QT', 'Nijmegen', '77-18787238', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Watson', 'The Hague', 169, '7555 QP', 'Hengelo', '46-08803009', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Clark', 'Utrecht', 115, '5046 IZ', 'Delft', '37-98555651', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Murphy', 'Utrecht', 28, '0428 JF', 'Hilversum', '51-80218094', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Wilson', 'Amsterdam', 116, '1301 KP', 'Den Haag', '08-18757264', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Collins', 'Rotterdam', 140, '5197 PT', 'Velsen', '24-90115735', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Brown', 'Eindhoven', 77, '7044 GV', 'Tilburg', '56-59323352', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'White', 'The Hague', 99, '3234 DP', 'Almere', '04-66843753', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Edwards', 'Amsterdam', 86, '9629 ZF', 'Hoofddorp', '15-71940735', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Peterson', 'Utrecht', 192, '8645 VV', 'Bergen op Zoom', '40-09150919', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Martin', 'Utrecht', 206, '7509 QU', 'Bergen op Zoom', '77-80165645', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Sanders', 'Amsterdam', 51, '7915 TQ', 'Enschede', '24-60424471', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Bailey', 'Rotterdam', 19, '5638 BB', 'Leeuwarden', '20-63791097', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Samantha', 'Hall', 'Eindhoven', 55, '5721 UR', 'Haarlem', '87-28362341', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'James', 'Rotterdam', 116, '6935 BU', 'Tilburg', '57-07735647', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Patterson', 'The Hague', 86, '6448 IY', 'Almere', '97-06034169', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Adams', 'The Hague', 117, '1362 YI', 'Breda', '04-02794643', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Wood', 'Amsterdam', 128, '3656 OX', 'Gouda', '80-71515926', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ella', 'Phillips', 'Rotterdam', 124, '5612 HQ', 'Heerlen', '04-44007272', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Parker', 'Utrecht', 99, '6428 NH', 'Amstelveen', '57-34912186', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Thomas', 'Eindhoven', 234, '6060 UP', 'Oss', '73-87970641', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Walker', 'Rotterdam', 58, '4761 NG', 'Oss', '83-26201495', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Lee', 'The Hague', 132, '5662 LM', 'Katwijk', '32-55866248', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Paisley', 'Campbell', 'Rotterdam', 159, '4491 WE', 'Almere', '05-99275868', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'White', 'Amsterdam', 67, '4868 HQ', 'Arnhem', '03-30887042', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Garcia', 'Eindhoven', 107, '7215 KA', 'Arnhem', '59-19603823', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Walker', 'Eindhoven', 178, '1744 DP', 'Spijkenisse', '81-22343981', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Hall', 'The Hague', 239, '0963 NK', 'Spijkenisse', '61-14341958', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Gray', 'Eindhoven', 244, '0429 FY', 'Velsen', '75-90527282', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Richardson', 'Eindhoven', 98, '9986 YB', 'Amersfoort', '29-07876946', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'Evans', 'The Hague', 166, '3649 VT', 'Amstelveen', '35-76011209', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Price', 'Eindhoven', 66, '6203 IK', 'Eindhoven', '83-77314236', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Rogers', 'Utrecht', 70, '1214 EU', 'Leeuwarden', '45-40230898', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Jones', 'Utrecht', 138, '8282 MC', 'Apeldoorn', '71-61480885', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Perez', 'Eindhoven', 191, '8237 XN', 'Heerlen', '23-10451305', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Bell', 'Rotterdam', 57, '1523 BG', 'Arnhem', '30-64274946', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Washington', 'The Hague', 122, '7558 UB', 'Spijkenisse', '79-85899113', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Thompson', 'Utrecht', 107, '2691 VO', 'Hilversum', '78-42460316', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Torres', 'The Hague', 154, '9979 SI', 'Almelo', '63-63103451', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Harris', 'The Hague', 236, '9438 HO', 'Nieuwegein', '31-63262912', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Coleman', 'Utrecht', 206, '3966 OS', 'Utrecht', '03-16464774', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'King', 'Eindhoven', 22, '1597 IP', 'Maastricht', '28-70162026', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Ross', 'Utrecht', 91, '4920 JX', 'Katwijk', '26-77095027', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Williams', 'Amsterdam', 180, '2148 YO', 'Utrecht', '17-49095285', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Evans', 'Utrecht', 23, '8688 UA', 'Spijkenisse', '99-13914628', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Wilson', 'Amsterdam', 125, '3506 XE', 'Gouda', '80-35044104', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Simmons', 'Rotterdam', 135, '3303 HJ', 'Lelystad', '15-69792167', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Allen', 'Eindhoven', 54, '4065 YT', 'Venlo', '46-73031819', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Ross', 'The Hague', 16, '9839 NP', 'Alkmaar', '43-21245119', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Johnson', 'Eindhoven', 191, '4093 BS', 'Arnhem', '17-15854459', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Jenkins', 'Utrecht', 204, '6563 WB', 'Maastricht', '91-07815222', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Hughes', 'Rotterdam', 112, '4637 IP', 'Assen', '44-23212343', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Jones', 'Utrecht', 127, '0491 KB', 'Nieuwegein', '89-32162652', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Cook', 'Rotterdam', 66, '7441 WP', 'Hoorn', '77-45059847', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Jones', 'Utrecht', 106, '9056 DB', 'Nieuwegein', '23-50443908', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Lewis', 'The Hague', 247, '2734 VP', 'Leiden', '67-22569886', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Ross', 'Utrecht', 97, '4292 KQ', 'Heerlen', '99-61653704', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Barnes', 'The Hague', 202, '3273 ZC', 'Zeist', '53-48691022', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Butler', 'Eindhoven', 117, '8257 CK', 'Zeist', '72-58490962', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Powell', 'Utrecht', 84, '8907 ZN', 'Deventer', '28-59977249', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Long', 'Rotterdam', 193, '5539 VL', 'Assen', '84-67962225', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Garcia', 'Utrecht', 36, '4485 DE', 'Assen', '88-32707132', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Allen', 'Rotterdam', 80, '3444 LT', 'Zaanstad', '78-37947939', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Lopez', 'Eindhoven', 96, '9137 CT', 'Zwolle', '49-09238409', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Perez', 'Utrecht', 221, '8246 CQ', 'Zwolle', '04-05573179', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Morris', 'Eindhoven', 176, '9580 ZI', 'Oss', '51-99282166', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Richardson', 'Amsterdam', 66, '4981 FE', 'Lelystad', '02-30202554', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Davis', 'Rotterdam', 34, '3158 DC', 'Roosendaal', '92-79262445', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Jackson', 'The Hague', 213, '3713 QB', 'Maastricht', '80-13013126', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Bailey', 'Rotterdam', 256, '0388 HT', 'Rotterdam', '35-20399196', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isla', 'Jackson', 'Amsterdam', 87, '2968 JM', 'Leeuwarden', '33-27112623', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Watson', 'The Hague', 74, '5284 LT', 'Lelystad', '67-21330117', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Thompson', 'Eindhoven', 99, '5327 TS', 'Eindhoven', '08-05111322', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Samantha', 'Hall', 'Utrecht', 198, '5884 HT', 'Alkmaar', '72-80108622', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Martinez', 'Eindhoven', 60, '9444 LX', 'Katwijk', '24-90869137', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'White', 'Amsterdam', 34, '1820 GX', 'Helmond', '26-60492832', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Torres', 'The Hague', 115, '0330 QY', 'Eindhoven', '33-60096644', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Taylor', 'Amsterdam', 48, '6860 KA', 'Gouda', '53-64742895', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Coleman', 'Rotterdam', 122, '7984 AK', 'Capelle aan den IJssel', '62-80866275', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Ward', 'Rotterdam', 74, '8177 OH', 'Bergen op Zoom', '78-48662830', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Robinson', 'The Hague', 53, '6943 HP', 'Capelle aan den IJssel', '45-07071474', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Ramirez', 'Utrecht', 37, '8671 RQ', 'Katwijk', '27-27151297', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Reed', 'Eindhoven', 107, '5882 GO', 'Venlo', '97-15200888', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Flores', 'Rotterdam', 64, '4085 XE', 'Zaanstad', '38-05046256', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Hughes', 'Rotterdam', 101, '0424 TI', 'Venlo', '21-04095605', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Robinson', 'Eindhoven', 20, '2941 EQ', 'Deventer', '85-96106983', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Collins', 'Amsterdam', 161, '9358 NO', 'Zwolle', '52-81356884', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emilia', 'Hughes', 'Eindhoven', 122, '9520 BM', 'Maastricht', '82-35660341', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Hughes', 'Eindhoven', 102, '7628 LB', 'Veenendaal', '67-02680823', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Gray', 'Amsterdam', 90, '6967 JM', 'Hoorn', '94-97095799', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Hernandez', 'Rotterdam', 232, '2490 OQ', 'Delft', '13-81374950', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Coleman', 'Amsterdam', 36, '0651 WG', 'Assen', '88-51352002', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Peterson', 'Eindhoven', 31, '9883 IQ', 'Dordrecht', '61-65919265', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Rivera', 'Eindhoven', 149, '7049 OB', 'Hoorn', '32-81221870', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Thomas', 'Utrecht', 9, '2703 HI', 'Zwolle', '40-69649760', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Wright', 'Utrecht', 52, '0758 CJ', 'Hoorn', '85-34434243', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Scott', 'Rotterdam', 190, '1713 EP', 'Leeuwarden', '36-26391301', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Lopez', 'Eindhoven', 152, '5958 SR', 'Amersfoort', '43-34433422', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Collins', 'Amsterdam', 140, '3770 ET', 'Hengelo', '82-13648489', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'White', 'Rotterdam', 4, '9223 MK', 'Hoorn', '70-19290056', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Simmons', 'Eindhoven', 24, '5326 BB', 'Hoorn', '79-90212514', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Scott', 'The Hague', 238, '1672 ZQ', 'Tilburg', '54-22949596', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'White', 'Eindhoven', 112, '1109 CJ', 'Purmerend', '05-21095230', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Carter', 'Amsterdam', 128, '7545 VG', 'Assen', '94-77424848', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Roberts', 'The Hague', 44, '1467 WH', 'Zaandam', '93-39592724', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Walker', 'Amsterdam', 38, '8299 IP', 'Zeist', '67-16693749', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Powell', 'The Hague', 7, '9672 MI', 'Zoetermeer', '03-19311782', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Samantha', 'Johnson', 'Utrecht', 83, '7940 CC', 'Oss', '27-82790888', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Ross', 'The Hague', 2, '3523 QF', 'Den Haag', '34-99148537', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Wright', 'Utrecht', 214, '3240 CH', 'Hilversum', '72-38093802', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Campbell', 'Eindhoven', 239, '2315 EB', 'Heerlen', '51-69576042', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alexa', 'Rogers', 'Rotterdam', 33, '3782 MD', 'Utrecht', '54-47226898', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Reed', 'Rotterdam', 211, '7450 SG', 'Hengelo', '75-14407784', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alice', 'Ross', 'The Hague', 192, '7389 CH', 'Dordrecht', '95-26371850', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Gray', 'Amsterdam', 6, '3444 XZ', 'Leiden', '12-76363387', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Cooper', 'Utrecht', 139, '1103 TQ', 'Groningen', '72-59247390', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Allen', 'Rotterdam', 7, '6240 PP', 'Spijkenisse', '28-30792889', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Harris', 'Rotterdam', 242, '7762 OU', 'Arnhem', '96-66752290', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Cox', 'Amsterdam', 165, '4689 YQ', 'Hoofddorp', '69-49490443', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Henderson', 'Utrecht', 75, '4988 RQ', 'Leeuwarden', '87-88332093', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Brown', 'Utrecht', 250, '2907 ZD', 'Velsen', '92-02680621', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Lopez', 'Amsterdam', 170, '4093 KP', 'Haarlem', '16-95871676', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Baker', 'Utrecht', 90, '4279 DV', 'Zoetermeer', '39-88156577', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Young', 'Eindhoven', 107, '9538 WH', 'Nieuwegein', '93-97117629', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Miller', 'The Hague', 163, '5011 DJ', 'Amsterdam', '18-17226817', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Perez', 'Rotterdam', 35, '3667 QG', 'Zeist', '37-21821488', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alice', 'Cooper', 'Utrecht', 174, '8331 RN', 'Delft', '67-84383023', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Allen', 'Rotterdam', 70, '2959 OX', 'Tilburg', '05-09894796', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isla', 'Morris', 'The Hague', 55, '6464 UA', 'Hengelo', '78-68924598', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Young', 'Amsterdam', 103, '2985 LD', 'Lelystad', '88-60435111', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Henderson', 'Utrecht', 219, '8002 MJ', 'Zaanstad', '54-12040166', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aubrey', 'Brown', 'Utrecht', 59, '0781 OS', 'Helmond', '94-90299173', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Wright', 'Utrecht', 193, '9197 TY', 'Utrecht', '71-32145701', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Gray', 'The Hague', 143, '1737 RA', 'Zeist', '94-10619170', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Morris', 'Rotterdam', 134, '1296 ME', 'Den Haag', '35-14391149', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Hughes', 'Utrecht', 147, '8175 HC', 'Bergen op Zoom', '96-35381691', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Nelson', 'Utrecht', 124, '3073 AJ', 'Delft', '11-85750315', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alexa', 'Martin', 'Amsterdam', 122, '7179 JE', 'Gouda', '90-09963783', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Kelly', 'Eindhoven', 43, '6639 HX', 'Velsen', '83-51110825', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Richardson', 'Utrecht', 162, '7147 BS', 'Zaanstad', '33-12497387', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Taylor', 'Rotterdam', 137, '2013 RI', 'Zwolle', '57-83286031', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Wright', 'Eindhoven', 55, '8975 BA', 'Amsterdam', '35-56812259', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Thomas', 'Rotterdam', 149, '4460 KJ', 'Bergen op Zoom', '31-49829186', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Richardson', 'Eindhoven', 36, '9561 VC', 'Almelo', '62-90971501', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Jackson', 'Utrecht', 99, '4980 OB', 'Maastricht', '49-67216397', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lillian', 'Perez', 'Rotterdam', 137, '6309 SZ', 'Den Haag', '07-12812409', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Coleman', 'Eindhoven', 206, '0535 FJ', 'Almere', '30-04518140', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Ramirez', 'Utrecht', 221, '1958 YG', 'Hengelo', '52-78886307', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Bell', 'Eindhoven', 2, '3340 JD', 'Zoetermeer', '31-89694014', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Flores', 'Utrecht', 195, '7641 AY', 'Maastricht', '25-29578198', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Clark', 'Utrecht', 13, '8941 IU', 'Arnhem', '93-82557210', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Ward', 'The Hague', 69, '2413 MS', 'Enschede', '29-66102548', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'Coleman', 'The Hague', 106, '4724 XM', 'Assen', '04-56964974', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Ross', 'The Hague', 130, '0248 SM', 'Leiden', '61-75198051', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Baker', 'Utrecht', 87, '9321 UL', 'Venlo', '76-55496929', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Perry', 'Utrecht', 207, '0260 QK', 'Zaanstad', '08-90973700', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Taylor', 'Eindhoven', 47, '3679 FQ', 'Alkmaar', '92-91756912', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Campbell', 'Eindhoven', 112, '1757 HN', 'Zeist', '00-15706736', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Hernandez', 'Rotterdam', 105, '8302 LT', 'Deventer', '78-85768746', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Thomas', 'The Hague', 223, '5780 GO', 'Rotterdam', '22-82188660', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Young', 'Rotterdam', 12, '8974 FL', 'Spijkenisse', '04-09482833', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Ramirez', 'The Hague', 157, '6549 NT', 'Oss', '46-15384970', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Jones', 'Rotterdam', 109, '9847 GP', 'Katwijk', '17-38119117', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Wright', 'Rotterdam', 57, '9241 QE', 'Leeuwarden', '40-32468091', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Torres', 'Utrecht', 180, '7013 KF', 'Vlaardingen', '76-15551369', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ella', 'Rogers', 'The Hague', 247, '5039 RX', 'Dordrecht', '13-26965690', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Coleman', 'The Hague', 165, '0244 DT', 'Lelystad', '27-15592324', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Sanders', 'Utrecht', 38, '9591 TK', 'Vlaardingen', '33-27427550', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Walker', 'Amsterdam', 144, '4794 NY', 'Haarlem', '35-86657185', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Baker', 'Amsterdam', 204, '6176 QZ', 'Capelle aan den IJssel', '15-79135320', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Smith', 'Utrecht', 223, '3213 ZF', 'Arnhem', '73-09833959', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Wright', 'Rotterdam', 104, '3189 VX', 'Roosendaal', '84-00404568', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Jenkins', 'Amsterdam', 244, '2722 YQ', 'Hengelo', '09-54186680', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Reed', 'Eindhoven', 23, '5667 UQ', 'Amstelveen', '75-06724864', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Morris', 'Utrecht', 133, '4435 OW', 'Leiden', '64-66991316', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Harris', 'Rotterdam', 155, '7071 UN', 'Helmond', '57-60212371', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Wood', 'Eindhoven', 169, '9151 VC', 'Bergen op Zoom', '46-02823644', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Paisley', 'Perry', 'Rotterdam', 176, '7438 KH', 'Deventer', '65-10984038', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Campbell', 'The Hague', 200, '4320 NZ', 'Gouda', '34-50226168', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Ward', 'The Hague', 119, '1595 MJ', 'Heerlen', '13-27267467', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'White', 'Utrecht', 38, '6333 LX', 'Eindhoven', '33-33205321', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Simmons', 'Utrecht', 84, '3489 RI', 'Arnhem', '54-59208401', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Martinez', 'The Hague', 20, '5305 HX', 'Groningen', '97-57927546', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Hill', 'The Hague', 5, '3312 XJ', 'Zwolle', '59-07419008', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Young', 'Utrecht', 242, '4679 JX', 'Katwijk', '81-65505122', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Taylor', 'Amsterdam', 40, '8977 OY', 'Eindhoven', '99-58944463', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Green', 'Utrecht', 247, '1264 JL', 'Zaanstad', '91-49553585', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Sanchez', 'Amsterdam', 139, '4246 FO', 'Haarlem', '24-36473671', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Long', 'The Hague', 133, '4502 SP', 'Utrecht', '60-80635268', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'Baker', 'The Hague', 52, '0832 LV', 'Lelystad', '71-79772719', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Campbell', 'Rotterdam', 226, '1231 GB', 'Hilversum', '10-02599066', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Scott', 'Eindhoven', 78, '8883 CH', 'Gouda', '44-32090437', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Wood', 'Utrecht', 147, '6847 EH', 'Oss', '06-20675495', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Evelyn', 'Stewart', 'Rotterdam', 55, '8270 EQ', 'Den Haag', '19-08806444', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Stewart', 'Utrecht', 194, '4372 YY', 'Maastricht', '19-21718230', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Mitchell', 'Eindhoven', 231, '9242 UQ', 'Nieuwegein', '95-90448687', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Rogers', 'Utrecht', 124, '1310 AC', 'Alkmaar', '51-94330336', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'White', 'Eindhoven', 236, '1230 PH', 'Zoetermeer', '39-94509833', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Ross', 'Eindhoven', 23, '0352 HI', 'Assen', '05-39320155', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Perry', 'Utrecht', 66, '4519 WS', 'Den Haag', '48-98393262', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emilia', 'Ward', 'Utrecht', 116, '8930 BE', 'Schiedam', '03-52832569', true);
insert into MOCK_DATA (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Flores', 'Utrecht', 53, '4886 KK', 'Velsen', '15-44307311', true);
