create table patienten (
	first_name VARCHAR(9),
	last_name VARCHAR(10),
	address VARCHAR(9),
	house_number INT,
	postcode VARCHAR(50),
	city VARCHAR(22),
	phone_number VARCHAR(50),
	active VARCHAR(50)
);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Wood', 'Amsterdam', 248, '6305 CC', 'Velsen', '65-76323004', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Long', 'Eindhoven', 155, '4454 SI', 'Roosendaal', '34-31904703', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Long', 'Amsterdam', 70, '4350 UU', 'Nijmegen', '60-84582212', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Edwards', 'The Hague', 48, '6517 WD', 'Venlo', '32-74463051', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Simmons', 'Rotterdam', 84, '8762 AF', 'Veenendaal', '14-28530662', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Jones', 'Amsterdam', 160, '9555 MU', 'Den Haag', '56-05617579', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Harris', 'Rotterdam', 245, '4963 RF', 'Dordrecht', '43-09341582', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Wood', 'Amsterdam', 122, '0596 GQ', 'Schiedam', '02-50751353', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Martinez', 'Amsterdam', 14, '4042 WZ', 'Maastricht', '75-72960657', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Walker', 'Amsterdam', 61, '6669 AD', 'Bergen op Zoom', '18-60953863', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Torres', 'Amsterdam', 120, '9422 QB', 'Heerlen', '31-98458223', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lillian', 'Wright', 'Amsterdam', 175, '8702 MX', 'Hengelo', '59-90097031', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kinsley', 'Powell', 'Rotterdam', 116, '8339 KE', 'Zoetermeer', '96-01338054', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Perry', 'Amsterdam', 160, '4293 LI', 'Almelo', '21-83982540', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'King', 'Amsterdam', 109, '1096 GW', 'Utrecht', '64-46855608', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Allen', 'Rotterdam', 208, '0460 EC', 'Bergen op Zoom', '59-29421868', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Phillips', 'Rotterdam', 86, '2410 UP', 'Spijkenisse', '66-09937548', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'James', 'Eindhoven', 240, '2244 NC', 'Velsen', '46-70412997', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aubrey', 'Rogers', 'The Hague', 14, '5718 LL', 'Enschede', '69-39078968', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Washington', 'Rotterdam', 245, '1611 NF', 'Rotterdam', '86-52451412', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Evans', 'Utrecht', 143, '9029 NK', 'Dordrecht', '97-10949756', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Thomas', 'Rotterdam', 86, '4809 RI', 'Zoetermeer', '28-34823343', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Cooper', 'Eindhoven', 3, '8158 VG', 'Purmerend', '38-95815214', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Johnson', 'Eindhoven', 142, '0543 JA', 'Hoofddorp', '33-00044425', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Hall', 'The Hague', 49, '4142 NG', 'Zaanstad', '13-11334440', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Campbell', 'Utrecht', 103, '6465 HP', 'Breda', '19-76465009', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Rivera', 'The Hague', 85, '5927 KT', 'Groningen', '59-46115264', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Powell', 'Utrecht', 17, '8169 KJ', 'Nieuwegein', '95-44658504', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Green', 'Eindhoven', 89, '0644 DH', 'Eindhoven', '42-76420465', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Peterson', 'Eindhoven', 24, '7370 ZQ', 'Leiden', '70-14425970', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Turner', 'Eindhoven', 189, '6650 BS', 'Schiedam', '16-37301769', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Jackson', 'Eindhoven', 103, '1302 CJ', 'Apeldoorn', '43-49146511', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'King', 'Amsterdam', 153, '6599 GO', 'Almelo', '13-76305421', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Clark', 'The Hague', 114, '2047 DD', 'Breda', '92-82130580', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Evans', 'Amsterdam', 41, '1814 QZ', 'Amstelveen', '01-59726064', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Scott', 'Utrecht', 206, '6067 AS', 'Almelo', '70-22823863', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Thomas', 'Rotterdam', 162, '2888 FI', 'Helmond', '24-23494104', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Ward', 'Eindhoven', 83, '1491 MW', 'Capelle aan den IJssel', '53-84275774', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Roberts', 'Amsterdam', 175, '2666 EU', 'Amersfoort', '30-05299384', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Paisley', 'Green', 'Rotterdam', 173, '3365 NA', 'Oss', '28-75755262', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Sanders', 'Utrecht', 221, '9731 ZA', 'Velsen', '89-41491235', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Mitchell', 'The Hague', 69, '2206 JX', 'Zwolle', '39-43215633', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Jackson', 'Amsterdam', 22, '4694 OC', 'Oss', '77-00108010', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Torres', 'Eindhoven', 61, '0454 YB', 'Helmond', '28-34100868', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Lewis', 'Utrecht', 56, '5971 WV', 'Hilversum', '99-58209566', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Phillips', 'Eindhoven', 8, '2097 EJ', 'Hengelo', '54-48336086', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eliana', 'Powell', 'The Hague', 11, '2482 TM', 'Amstelveen', '88-71488491', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Walker', 'The Hague', 77, '4630 GA', 'Arnhem', '52-19330958', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Morris', 'Rotterdam', 57, '5768 BZ', 'Velsen', '24-96914535', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Parker', 'Eindhoven', 244, '3050 QB', 'Breda', '76-06055649', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Williams', 'Rotterdam', 242, '0132 GL', 'Almelo', '35-75575113', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Reed', 'Rotterdam', 223, '5091 BC', 'Nieuwegein', '79-88240442', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Cox', 'The Hague', 97, '0763 UK', 'Gouda', '56-28945283', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Richardson', 'Eindhoven', 76, '0065 UC', 'Hoofddorp', '25-68436828', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eliana', 'Walker', 'Utrecht', 130, '0679 JV', 'Breda', '22-34152711', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Barnes', 'Utrecht', 140, '4478 GT', 'Hilversum', '48-99814516', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Hernandez', 'Eindhoven', 80, '6731 LG', 'Zwolle', '00-75746526', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Kelly', 'The Hague', 151, '1829 QA', 'Apeldoorn', '70-05781868', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Rivera', 'Rotterdam', 63, '1394 FV', 'Hoorn', '73-93660355', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Clark', 'Utrecht', 45, '1630 WH', 'Hengelo', '80-73268903', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Carter', 'Amsterdam', 74, '2216 DH', 'Delft', '15-21510541', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Martin', 'Utrecht', 2, '7710 FN', 'Den Haag', '48-68177796', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Edwards', 'Utrecht', 72, '5153 YA', 'Purmerend', '56-13350951', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Butler', 'Amsterdam', 43, '9199 UA', 'Leeuwarden', '67-45797589', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Collins', 'Utrecht', 204, '7879 MC', 'Roosendaal', '86-62257808', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Young', 'Utrecht', 234, '9018 HY', 'Vlaardingen', '55-91005695', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Martin', 'Eindhoven', 252, '6549 EG', 'Almelo', '19-58479057', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Addison', 'Williams', 'Rotterdam', 166, '5946 GL', 'Heerlen', '49-79996971', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Turner', 'Rotterdam', 87, '7897 ES', 'Bergen op Zoom', '42-71286211', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Parker', 'Utrecht', 97, '5847 DN', 'Zeist', '47-62751980', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Walker', 'Rotterdam', 131, '8276 FA', 'Alkmaar', '75-28905815', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Nelson', 'Rotterdam', 222, '4563 NI', 'Deventer', '79-48252802', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Walker', 'Eindhoven', 88, '9477 CW', 'Zwolle', '76-13245146', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Garcia', 'Rotterdam', 128, '4958 PB', 'Helmond', '19-03725142', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Smith', 'Utrecht', 23, '8278 QI', 'Dordrecht', '73-86424932', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Jones', 'Amsterdam', 77, '3686 ZO', 'Hilversum', '31-35326901', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Miller', 'Amsterdam', 184, '1402 MJ', 'Rotterdam', '07-14739074', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Lewis', 'Amsterdam', 186, '2578 CC', 'Helmond', '43-90738637', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Baker', 'The Hague', 198, '8623 UE', 'Zwolle', '83-67804027', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Nelson', 'Amsterdam', 223, '1746 JN', 'Hoorn', '43-45551009', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Jones', 'Utrecht', 141, '5261 MB', 'Zaandam', '41-01982923', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Murphy', 'Eindhoven', 83, '0901 FM', 'Bergen op Zoom', '84-79125925', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Wood', 'Amsterdam', 210, '3438 VG', 'Groningen', '98-55885591', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Roberts', 'Amsterdam', 210, '0443 UV', 'Utrecht', '39-43417662', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Howard', 'Eindhoven', 156, '4204 VD', 'Spijkenisse', '00-93600612', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Green', 'Eindhoven', 45, '2194 EP', 'Amstelveen', '24-55968535', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Parker', 'Utrecht', 70, '8158 JD', 'Vlaardingen', '79-24796885', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Sanders', 'Eindhoven', 159, '6881 XG', 'Katwijk', '96-56130294', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Wood', 'The Hague', 40, '4099 UD', 'Rotterdam', '35-12476886', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Rogers', 'The Hague', 50, '0566 HH', 'Nieuwegein', '80-31466965', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Simmons', 'The Hague', 2, '5049 SF', 'Apeldoorn', '51-15549462', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Wood', 'Utrecht', 40, '6574 SG', 'Spijkenisse', '15-85845631', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Edwards', 'Utrecht', 134, '9413 GX', 'Bergen op Zoom', '78-35223838', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Collins', 'The Hague', 37, '7823 ZG', 'Zwolle', '83-23783635', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Young', 'Eindhoven', 199, '4657 LQ', 'Amstelveen', '02-21409087', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'James', 'The Hague', 11, '8515 GE', 'Heerlen', '29-28081681', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Reed', 'Rotterdam', 118, '2160 FK', 'Katwijk', '98-50855211', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Rivera', 'Utrecht', 184, '0808 WT', 'Roosendaal', '52-39146162', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Ward', 'The Hague', 117, '1044 OQ', 'Alkmaar', '94-87908789', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Kelly', 'Amsterdam', 187, '5237 EM', 'Apeldoorn', '39-74284051', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Sanchez', 'Rotterdam', 29, '0536 VS', 'Eindhoven', '92-43429925', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Evans', 'Rotterdam', 83, '1452 LU', 'Capelle aan den IJssel', '28-48877377', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Collins', 'Amsterdam', 128, '5712 VT', 'Lelystad', '93-13964283', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Morris', 'Amsterdam', 41, '0583 YR', 'Hilversum', '39-28623200', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Walker', 'Rotterdam', 74, '8798 NU', 'Vlaardingen', '60-31580814', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Adams', 'Eindhoven', 100, '0690 CE', 'Hoorn', '89-50871354', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Kelly', 'Rotterdam', 213, '3341 RX', 'Schiedam', '55-04006079', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Phillips', 'Rotterdam', 155, '3331 UU', 'Amersfoort', '11-94462866', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Anderson', 'The Hague', 90, '6084 EA', 'Almelo', '71-87782493', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'Evans', 'Eindhoven', 230, '9402 CS', 'Oss', '09-73820249', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Gonzalez', 'Amsterdam', 29, '9779 ZV', 'Leiden', '85-11021319', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Gonzalez', 'Amsterdam', 174, '7182 UK', 'Zwolle', '24-00186710', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Lopez', 'Amsterdam', 229, '9935 WR', 'Oss', '46-88641740', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Ross', 'Rotterdam', 202, '9617 IA', 'Zoetermeer', '42-15887579', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Rivera', 'Utrecht', 164, '6426 XG', 'Utrecht', '44-79227473', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Parker', 'The Hague', 135, '7359 UF', 'Utrecht', '17-07074020', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Bailey', 'Rotterdam', 256, '8677 UO', 'Velsen', '43-37259924', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Wright', 'The Hague', 85, '9979 NJ', 'Amsterdam', '56-97977342', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Allen', 'Rotterdam', 1, '4931 XC', 'Hengelo', '59-02429977', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Miller', 'Utrecht', 39, '2535 QZ', 'Schiedam', '06-24863550', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Price', 'Eindhoven', 6, '5629 CA', 'Tilburg', '74-12501791', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Powell', 'Amsterdam', 96, '6268 SJ', 'Alkmaar', '51-15168908', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Simmons', 'Eindhoven', 193, '8736 RG', 'Capelle aan den IJssel', '49-32264708', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Gray', 'Rotterdam', 92, '7250 WD', 'Purmerend', '42-01563989', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Brooks', 'Rotterdam', 153, '8009 AY', 'Arnhem', '72-51356397', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Baker', 'Amsterdam', 237, '3211 PH', 'Nieuwegein', '10-78264206', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Long', 'The Hague', 153, '0573 EY', 'Groningen', '68-44294653', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Perez', 'Rotterdam', 74, '7387 OA', 'Breda', '29-04861550', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Coleman', 'Eindhoven', 184, '8884 BS', 'Zeist', '32-99008597', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kinsley', 'Richardson', 'The Hague', 209, '9740 EH', 'Almere', '94-20744450', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Jenkins', 'Eindhoven', 91, '2538 LH', 'Veenendaal', '05-00532927', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Ross', 'Rotterdam', 172, '3736 NB', 'Zaanstad', '55-72588796', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Cox', 'Eindhoven', 126, '0857 PS', 'Hoorn', '15-56392957', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Butler', 'Amsterdam', 6, '3007 FN', 'Hilversum', '00-93009795', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Smith', 'Amsterdam', 40, '0049 DF', 'Bergen op Zoom', '09-29203132', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'Hernandez', 'Rotterdam', 83, '0551 PX', 'Vlaardingen', '15-76572154', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Butler', 'Rotterdam', 251, '0960 DA', 'Leiden', '81-05244939', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Peterson', 'The Hague', 244, '1813 YW', 'Tilburg', '76-14561497', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Robinson', 'The Hague', 59, '6173 SD', 'Apeldoorn', '68-18941585', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Flores', 'Eindhoven', 7, '2627 XC', 'Velsen', '92-58608826', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Bennett', 'Rotterdam', 40, '2512 SJ', 'Rotterdam', '41-91632245', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Johnson', 'The Hague', 208, '4450 AP', 'Haarlem', '92-31234987', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'James', 'Utrecht', 107, '4435 SC', 'Apeldoorn', '18-16589517', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Young', 'Utrecht', 146, '3990 RW', 'Utrecht', '53-18155007', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Lopez', 'Rotterdam', 219, '6532 BQ', 'Amstelveen', '15-26100511', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Evans', 'Utrecht', 114, '1784 YU', 'Utrecht', '34-60521061', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Gray', 'The Hague', 30, '4827 GE', 'Den Haag', '98-27497696', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Campbell', 'Utrecht', 82, '7441 OI', 'Spijkenisse', '26-86866638', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Cook', 'Eindhoven', 124, '5577 HD', 'Groningen', '87-03129006', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Green', 'The Hague', 112, '6302 GD', 'Hilversum', '12-53952500', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Powell', 'Rotterdam', 100, '3291 YU', 'Gouda', '75-68533800', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Powell', 'The Hague', 115, '2066 SW', 'Capelle aan den IJssel', '42-17482049', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Ramirez', 'Utrecht', 132, '3828 IW', 'Hengelo', '38-87990088', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aurora', 'Garcia', 'Utrecht', 239, '3179 OZ', 'Zaandam', '74-07124481', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Wilson', 'The Hague', 136, '3908 GY', 'Gouda', '82-09024819', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Flores', 'Amsterdam', 227, '2358 JQ', 'Leiden', '18-52484597', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Sanders', 'Amsterdam', 47, '1262 ZW', 'Purmerend', '45-12024289', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Collins', 'Eindhoven', 10, '0317 PX', 'Deventer', '94-27569480', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'White', 'Eindhoven', 35, '1663 QW', 'Dordrecht', '89-10162397', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Thomas', 'Utrecht', 106, '1341 DO', 'Zoetermeer', '41-68609309', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Butler', 'Amsterdam', 221, '9782 AC', 'Alkmaar', '35-84321532', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Murphy', 'Rotterdam', 96, '3037 LH', 'Assen', '61-90741733', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Hall', 'Utrecht', 180, '6355 QZ', 'Assen', '63-80054865', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Price', 'Amsterdam', 174, '4477 OL', 'Zwolle', '75-43289279', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Nelson', 'Rotterdam', 57, '0187 RR', 'Zoetermeer', '35-96903255', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Bailey', 'Eindhoven', 233, '5389 UH', 'Almelo', '61-68941868', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Parker', 'Eindhoven', 92, '3350 NA', 'Apeldoorn', '09-58283551', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Davis', 'Amsterdam', 61, '1739 EE', 'Schiedam', '68-41777107', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Evans', 'Rotterdam', 196, '8484 TP', 'Lelystad', '69-91317366', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'Sanders', 'Eindhoven', 192, '8391 SE', 'Leeuwarden', '05-25671678', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Jenkins', 'Rotterdam', 189, '4422 CV', 'Hoofddorp', '97-50987515', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Hill', 'Eindhoven', 106, '3294 FC', 'Amersfoort', '69-08593012', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aubrey', 'Powell', 'Utrecht', 101, '2693 AQ', 'Lelystad', '00-71744117', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Taylor', 'The Hague', 139, '6896 DF', 'Capelle aan den IJssel', '58-83835728', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Powell', 'Eindhoven', 98, '1394 XJ', 'Eindhoven', '57-00673440', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eliana', 'Gray', 'Utrecht', 239, '3683 PZ', 'Zaandam', '32-56988399', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Phillips', 'Amsterdam', 106, '5873 KP', 'Venlo', '80-67295903', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Hernandez', 'The Hague', 77, '6772 SI', 'Spijkenisse', '65-32135728', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Jones', 'Utrecht', 203, '7806 JQ', 'Zaanstad', '27-71094602', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Rodriguez', 'Amsterdam', 217, '3325 LS', 'Gouda', '26-97874615', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Scott', 'Utrecht', 134, '5586 CO', 'Oss', '26-25612446', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Hughes', 'Rotterdam', 159, '6238 MV', 'Hoorn', '30-68762807', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Sanchez', 'Amsterdam', 252, '4682 JM', 'Rotterdam', '31-05731917', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Perry', 'Utrecht', 186, '5722 HU', 'Dordrecht', '65-23358959', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Ross', 'The Hague', 149, '6841 NW', 'Rotterdam', '77-66530905', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Moore', 'Utrecht', 76, '4392 TS', 'Nieuwegein', '91-70703030', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Bell', 'Amsterdam', 112, '8582 QH', 'Assen', '68-77532911', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Wilson', 'Amsterdam', 122, '2896 OQ', 'Assen', '42-11863071', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Collins', 'Eindhoven', 139, '2294 NB', 'Purmerend', '19-24185001', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Howard', 'Utrecht', 81, '5409 TD', 'Delft', '37-38496149', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aurora', 'Baker', 'Utrecht', 73, '4648 RT', 'Zwolle', '69-18451853', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Butler', 'Utrecht', 101, '1291 RU', 'Purmerend', '48-57428593', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Kelly', 'Amsterdam', 140, '4654 PS', 'Oss', '53-07466908', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Ward', 'Amsterdam', 191, '2311 RN', 'Zwolle', '89-51635633', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Robinson', 'Eindhoven', 204, '2748 GX', 'Zaanstad', '04-50598027', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Rodriguez', 'Rotterdam', 17, '8858 YB', 'Haarlem', '33-30996068', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Bailey', 'The Hague', 209, '9362 MS', 'Capelle aan den IJssel', '63-18094990', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aaliyah', 'Allen', 'The Hague', 193, '6058 PM', 'Breda', '32-87370642', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'White', 'Utrecht', 168, '1092 ER', 'Vlaardingen', '18-25723117', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Davis', 'The Hague', 211, '8203 LW', 'Zoetermeer', '43-31323034', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Peterson', 'Rotterdam', 161, '5005 GS', 'Dordrecht', '59-91530797', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Gray', 'Eindhoven', 98, '4279 FC', 'Heerlen', '84-87857849', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alice', 'Parker', 'Eindhoven', 37, '2173 DA', 'Hengelo', '77-32772706', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Wood', 'Rotterdam', 164, '6802 TS', 'Nijmegen', '30-42819965', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Jackson', 'Utrecht', 13, '6722 DY', 'Zaandam', '49-16194903', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Reed', 'Rotterdam', 82, '5438 OM', 'Zeist', '30-25027581', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Bell', 'Amsterdam', 68, '8527 XK', 'Lelystad', '28-34270204', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Barnes', 'The Hague', 137, '6593 OA', 'Heerlen', '48-59044583', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Rivera', 'Utrecht', 102, '9758 JY', 'Velsen', '08-57071647', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Moore', 'The Hague', 50, '5709 AS', 'Almelo', '01-68621715', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Howard', 'The Hague', 22, '4080 HS', 'Katwijk', '25-42741559', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Walker', 'Utrecht', 227, '9262 QX', 'Amsterdam', '99-46475214', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Howard', 'Eindhoven', 199, '4398 RA', 'Haarlem', '35-48298745', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Jenkins', 'Rotterdam', 145, '3285 ZE', 'Veenendaal', '50-29826005', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Patterson', 'Rotterdam', 168, '3296 CR', 'Deventer', '77-37269742', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Washington', 'Amsterdam', 79, '9638 MC', 'Helmond', '02-13777260', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Nelson', 'Rotterdam', 124, '7845 BI', 'Hoorn', '26-84942822', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Harris', 'Rotterdam', 147, '8800 TH', 'Breda', '27-44585276', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'James', 'Rotterdam', 119, '8616 QH', 'Hilversum', '30-77527325', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Perez', 'Eindhoven', 239, '6032 GN', 'Breda', '65-26269914', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Price', 'Eindhoven', 52, '5959 RY', 'Hoofddorp', '42-66659281', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'King', 'Utrecht', 53, '0577 GP', 'Hoofddorp', '80-70540562', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ella', 'Young', 'Eindhoven', 233, '3069 HM', 'Purmerend', '36-03032812', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Davis', 'Amsterdam', 68, '4918 JO', 'Capelle aan den IJssel', '15-38664276', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Williams', 'Amsterdam', 20, '7439 HK', 'Amstelveen', '82-40609697', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Jones', 'Utrecht', 128, '2521 UE', 'Arnhem', '48-35925843', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Ramirez', 'Eindhoven', 204, '0173 VE', 'Rotterdam', '82-36408422', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Collins', 'Eindhoven', 79, '3344 OG', 'Amersfoort', '36-84733795', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Garcia', 'Eindhoven', 107, '2560 ZB', 'Alkmaar', '16-12988642', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Cook', 'Rotterdam', 142, '0696 RO', 'Deventer', '05-54764231', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Young', 'The Hague', 210, '0122 BP', 'Leiden', '91-92828890', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lillian', 'Martinez', 'The Hague', 12, '5148 LI', 'Rotterdam', '68-76455466', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Butler', 'Utrecht', 109, '9759 WH', 'Groningen', '70-54997271', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Nelson', 'Utrecht', 119, '5692 QQ', 'Almere', '90-63360229', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Jones', 'The Hague', 5, '7587 CP', 'Zoetermeer', '72-46855043', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Simmons', 'Eindhoven', 160, '9281 HJ', 'Zoetermeer', '24-67046837', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Jenkins', 'Rotterdam', 132, '2063 VG', 'Assen', '67-85234825', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Flores', 'Eindhoven', 236, '1225 GQ', 'Hilversum', '20-82703829', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Stewart', 'Amsterdam', 47, '2887 XT', 'Lelystad', '08-68519482', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Young', 'Utrecht', 164, '6984 JW', 'Dordrecht', '55-01797534', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Rivera', 'Utrecht', 195, '8988 DM', 'Amsterdam', '10-95571516', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Thompson', 'Amsterdam', 148, '9102 AP', 'Rotterdam', '37-46790179', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Ross', 'Eindhoven', 174, '0935 VV', 'Zoetermeer', '12-78439644', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elena', 'Rodriguez', 'Utrecht', 117, '1361 WU', 'Apeldoorn', '92-09624359', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Cook', 'The Hague', 216, '5197 KB', 'Eindhoven', '11-82855467', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Patterson', 'Amsterdam', 196, '4157 AV', 'Dordrecht', '57-63107356', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Martin', 'The Hague', 185, '6707 KU', 'Breda', '83-99619106', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Jackson', 'The Hague', 50, '4668 QH', 'Helmond', '11-96099740', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Jenkins', 'Amsterdam', 127, '2397 CB', 'Rotterdam', '13-32799653', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Rogers', 'Eindhoven', 11, '7456 ST', 'Groningen', '14-17363383', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Brown', 'Rotterdam', 98, '5706 PI', 'Spijkenisse', '51-43322218', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Thompson', 'Rotterdam', 94, '1948 TD', 'Bergen op Zoom', '36-60758008', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'King', 'Utrecht', 234, '6218 VS', 'Assen', '13-66914670', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Cook', 'The Hague', 248, '3495 JN', 'Zaanstad', '80-69522998', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Murphy', 'The Hague', 226, '1498 DZ', 'Arnhem', '78-27480956', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Thompson', 'The Hague', 90, '0328 DM', 'Arnhem', '47-05399513', true);
