insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'Gowanlock', '789 Oak Ln', 216, '0094 RI', 'Groningen', '64-38121125', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Ivanyushin', '123 Main St', 24, '0156 BP', 'Groningen', '46-10324896', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Ludovico', '123 Main St', 92, '2003 TM', 'Breda', '19-81962042', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Amelia', 'De La Hay', '123 Main St', 36, '7618 ZM', 'Almere', '56-77624166', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hannah', 'Whitehead', '789 Oak Ln', 4, '4402 SJ', 'Den Haag', '74-22462419', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Boarleyson', '789 Oak Ln', 31, '0315 BN', 'Den Haag', '13-70961640', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Moore', '123 Main St', 229, '6474 UZ', 'Almere', '55-57054308', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nova', 'Falloon', '123 Main St', 17, '1355 OS', 'Tilburg', '71-81438428', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Julia', 'Wason', '789 Oak Ln', 108, '3264 DC', 'Eindhoven', '65-28677219', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lillian', 'Gebbie', '456 Elm Ave', 8, '6417 DX', 'Nijmegen', '64-36793588', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nevaeh', 'Yglesias', '456 Elm Ave', 207, '7199 PJ', 'Rotterdam', '66-30240625', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Brashier', '456 Elm Ave', 124, '3613 WW', 'Rotterdam', '04-87561566', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Paolino', '456 Elm Ave', 156, '7782 NH', 'Utrecht', '40-71499967', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Fylan', '456 Elm Ave', 192, '0056 MS', 'Tilburg', '01-05516889', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aurora', 'Lewsey', '456 Elm Ave', 192, '0866 QY', 'Eindhoven', '95-06659121', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Servant', '123 Main St', 104, '4770 AN', 'Den Haag', '87-24570069', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Strivens', '789 Oak Ln', 22, '6020 PU', 'Den Haag', '33-70627678', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Jodkowski', '456 Elm Ave', 127, '8004 NK', 'Den Haag', '20-40789842', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Coutthart', '789 Oak Ln', 215, '6513 IS', 'Tilburg', '71-89095593', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emery', 'Chidgey', '123 Main St', 25, '0219 CA', 'Den Haag', '23-31503152', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Cubin', '456 Elm Ave', 66, '8485 WP', 'Nijmegen', '18-31842399', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Bastick', '123 Main St', 77, '3738 RW', 'Nijmegen', '95-88967785', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Dann', '789 Oak Ln', 97, '8717 HY', 'Nijmegen', '86-10208991', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Pearn', '789 Oak Ln', 114, '1054 BM', 'Breda', '61-18997309', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Cradoc', '456 Elm Ave', 176, '1073 TM', 'Den Haag', '34-72171522', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Easman', '456 Elm Ave', 21, '9917 TX', 'Tilburg', '34-43188224', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Dell Casa', '123 Main St', 15, '4617 JZ', 'Tilburg', '63-76795587', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Kavanagh', '456 Elm Ave', 102, '4598 YQ', 'Tilburg', '13-58597398', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emily', 'Norrie', '456 Elm Ave', 4, '0356 AR', 'Almere', '05-48516383', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Mariot', '456 Elm Ave', 70, '0912 AV', 'Nijmegen', '22-94708175', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Terron', '123 Main St', 31, '5332 XG', 'Nijmegen', '70-11816679', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eliana', 'Gogan', '456 Elm Ave', 115, '2865 LL', 'Groningen', '86-93810945', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Davidof', '123 Main St', 45, '4779 IN', 'Almere', '98-41957494', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eliana', 'Ixer', '789 Oak Ln', 157, '0749 FQ', 'Eindhoven', '45-96366491', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Perone', '456 Elm Ave', 246, '3596 WJ', 'Utrecht', '66-62060627', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Nossent', '123 Main St', 195, '2530 DI', 'Rotterdam', '73-69220582', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emilia', 'Chue', '123 Main St', 169, '4694 DU', 'Rotterdam', '09-05548878', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Sutcliff', '789 Oak Ln', 203, '2135 VI', 'Amsterdam', '01-01413601', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Antonioni', '456 Elm Ave', 187, '8369 YD', 'Tilburg', '20-16085410', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Amaya', '456 Elm Ave', 27, '5024 OP', 'Almere', '14-25432748', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Tonkes', '456 Elm Ave', 196, '8826 NV', 'Almere', '11-52560914', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Dunsmore', '123 Main St', 41, '0025 SI', 'Groningen', '41-38349203', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Bendelow', '456 Elm Ave', 248, '4544 LM', 'Rotterdam', '89-31963354', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Frain', '456 Elm Ave', 182, '8794 WT', 'Groningen', '46-54826125', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Woodworth', '456 Elm Ave', 252, '1726 FX', 'Nijmegen', '31-27216018', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Westfalen', '456 Elm Ave', 221, '8499 OV', 'Rotterdam', '58-00293995', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Wimms', '789 Oak Ln', 17, '0293 QE', 'Nijmegen', '32-27616743', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Rainer', '456 Elm Ave', 112, '0923 FS', 'Utrecht', '95-95114110', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Brabben', '456 Elm Ave', 67, '8405 TC', 'Breda', '70-00736473', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Roebottom', '789 Oak Ln', 203, '3597 AA', 'Amsterdam', '28-67267615', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Larroway', '789 Oak Ln', 5, '9936 XH', 'Utrecht', '95-90939430', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Charlotte', 'Shwenn', '123 Main St', 155, '3747 PP', 'Almere', '00-36566404', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Tonepohl', '123 Main St', 193, '3734 PT', 'Tilburg', '17-63421359', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Penelope', 'Ogden', '456 Elm Ave', 100, '7695 ZQ', 'Nijmegen', '02-81017897', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Sustin', '789 Oak Ln', 65, '3270 VO', 'Amsterdam', '20-57446855', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Lyptrade', '789 Oak Ln', 228, '7865 CD', 'Utrecht', '18-85969591', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Audrey', 'Brightie', '789 Oak Ln', 128, '8098 LU', 'Breda', '46-14861886', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Paisley', 'Steeden', '123 Main St', 127, '3039 NK', 'Rotterdam', '68-41013015', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Biggerdike', '123 Main St', 7, '8849 RO', 'Tilburg', '42-62544298', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Ebben', '789 Oak Ln', 122, '0016 JT', 'Eindhoven', '31-25592304', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Harper', 'Smillie', '123 Main St', 236, '2277 WZ', 'Rotterdam', '62-04698629', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isla', 'Mohammad', '789 Oak Ln', 54, '2447 PD', 'Nijmegen', '95-68413151', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Chateau', '123 Main St', 64, '2443 YC', 'Amsterdam', '12-35265605', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Moryson', '123 Main St', 182, '1785 GK', 'Eindhoven', '92-61263644', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Trow', '456 Elm Ave', 103, '3090 HI', 'Utrecht', '43-79227745', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Twinborough', '456 Elm Ave', 153, '8878 TJ', 'Tilburg', '55-92129007', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Piper', 'Siward', '789 Oak Ln', 191, '2477 DY', 'Rotterdam', '66-37864140', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mia', 'Evert', '123 Main St', 141, '5792 RT', 'Eindhoven', '50-61132335', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Oury', '789 Oak Ln', 250, '6173 DP', 'Rotterdam', '09-76673315', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Leall', '789 Oak Ln', 204, '0513 CR', 'Almere', '03-95468165', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Gunter', '456 Elm Ave', 235, '5898 HO', 'Amsterdam', '68-02810946', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Augustus', '123 Main St', 227, '8225 FF', 'Nijmegen', '86-26789161', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ella', 'Asif', '789 Oak Ln', 155, '1669 SN', 'Nijmegen', '18-54733392', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Tunesi', '456 Elm Ave', 200, '0630 XX', 'Breda', '73-84380484', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Conrart', '456 Elm Ave', 225, '6457 OM', 'Utrecht', '27-63855059', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Durbyn', '789 Oak Ln', 53, '5514 DC', 'Rotterdam', '32-10004157', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alexa', 'Bartlomiejczyk', '123 Main St', 68, '1366 TA', 'Almere', '42-05515764', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kinsley', 'Trace', '123 Main St', 190, '9918 JM', 'Nijmegen', '87-97929939', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Mila', 'Simion', '789 Oak Ln', 114, '3710 IL', 'Utrecht', '83-75587629', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Docker', '456 Elm Ave', 171, '1596 RN', 'Rotterdam', '02-13955411', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Whaley', '456 Elm Ave', 113, '6235 PF', 'Almere', '39-34114262', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Krabbe', '123 Main St', 256, '8563 UF', 'Rotterdam', '87-42262986', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'McFee', '123 Main St', 68, '0360 KZ', 'Eindhoven', '94-76690632', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Gundry', '456 Elm Ave', 206, '2084 AR', 'Breda', '01-55189123', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Brisco', '123 Main St', 172, '4403 GA', 'Groningen', '85-55156261', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emilia', 'Jakoubek', '456 Elm Ave', 226, '5933 CY', 'Eindhoven', '46-03362785', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Infantino', '789 Oak Ln', 150, '5378 IU', 'Almere', '69-05162298', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Hache', '456 Elm Ave', 140, '9723 GX', 'Breda', '69-81799604', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Schmuhl', '123 Main St', 39, '3910 ZI', 'Amsterdam', '31-04667118', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Dainty', '456 Elm Ave', 23, '6274 SL', 'Den Haag', '03-81434867', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Birrell', '456 Elm Ave', 34, '4771 SJ', 'Tilburg', '60-56574789', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Addison', 'Mieville', '456 Elm Ave', 111, '2905 HE', 'Almere', '90-16740081', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madelyn', 'Samber', '789 Oak Ln', 89, '7078 AJ', 'Utrecht', '75-34231016', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Deble', '789 Oak Ln', 25, '2313 UE', 'Nijmegen', '81-37595837', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Dettmar', '789 Oak Ln', 204, '4705 ZL', 'Breda', '39-01293348', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Mingaud', '456 Elm Ave', 211, '7181 VW', 'Den Haag', '30-96694246', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Huban', '789 Oak Ln', 252, '6234 EJ', 'Amsterdam', '12-66706688', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Gotthard', '789 Oak Ln', 177, '6114 CD', 'Utrecht', '21-12420662', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Ainscough', '789 Oak Ln', 165, '1986 DL', 'Rotterdam', '90-04596185', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Keen', '123 Main St', 27, '5389 VX', 'Nijmegen', '02-10232725', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Hugonet', '456 Elm Ave', 254, '3653 DX', 'Rotterdam', '65-75330622', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Marikhin', '789 Oak Ln', 98, '7232 LM', 'Breda', '38-84332523', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Riley', 'Moakler', '456 Elm Ave', 7, '9005 UQ', 'Den Haag', '07-18928907', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'De Souza', '123 Main St', 190, '1889 WH', 'Groningen', '39-67876057', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aubrey', 'Munby', '456 Elm Ave', 39, '5832 BK', 'Amsterdam', '46-41106936', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Esmead', '789 Oak Ln', 127, '5745 WC', 'Eindhoven', '04-91518959', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Terbruggen', '456 Elm Ave', 18, '4641 NM', 'Nijmegen', '38-03152055', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alice', 'Bartles', '123 Main St', 165, '9088 EN', 'Rotterdam', '69-66272943', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Provis', '456 Elm Ave', 62, '3257 DK', 'Tilburg', '96-60532215', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Madison', 'Dullingham', '456 Elm Ave', 19, '6097 ID', 'Nijmegen', '08-93792544', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Trippick', '123 Main St', 208, '4373 HH', 'Nijmegen', '47-85881925', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'McRamsey', '456 Elm Ave', 241, '1433 HS', 'Amsterdam', '42-85211793', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'McPeck', '456 Elm Ave', 219, '6111 AX', 'Den Haag', '22-77947450', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Meryett', '789 Oak Ln', 57, '8247 HX', 'Groningen', '31-08616108', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Edeson', '456 Elm Ave', 40, '9303 FI', 'Almere', '92-32826908', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Segot', '456 Elm Ave', 102, '5442 DD', 'Rotterdam', '03-99738437', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Tootell', '789 Oak Ln', 134, '1320 MT', 'Breda', '52-93090686', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Karle', '789 Oak Ln', 4, '0763 FP', 'Groningen', '15-79587150', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Lawlie', '456 Elm Ave', 218, '1682 DZ', 'Nijmegen', '87-23845752', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Ilyasov', '789 Oak Ln', 212, '2421 JV', 'Den Haag', '54-77775032', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Phaup', '456 Elm Ave', 130, '6831 DB', 'Amsterdam', '28-67590976', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Rizon', '789 Oak Ln', 58, '2506 TT', 'Tilburg', '17-88149182', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Blaver', '789 Oak Ln', 198, '6778 GR', 'Groningen', '16-46720174', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Dissman', '456 Elm Ave', 200, '5209 FR', 'Rotterdam', '40-09737837', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aubrey', 'Pollastrone', '123 Main St', 239, '3120 YN', 'Groningen', '12-68115005', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Malsher', '123 Main St', 133, '5396 GH', 'Utrecht', '82-59312199', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Goscomb', '123 Main St', 185, '5814 UZ', 'Utrecht', '62-11436838', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'McCurtin', '456 Elm Ave', 190, '9306 YV', 'Amsterdam', '37-04709209', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Charlotte', 'Guidi', '123 Main St', 233, '0486 JY', 'Nijmegen', '06-11832109', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aurora', 'Downes', '123 Main St', 85, '9086 YA', 'Utrecht', '16-69088944', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Smittoune', '123 Main St', 28, '8183 EO', 'Nijmegen', '91-00960892', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Cattermull', '456 Elm Ave', 230, '3228 QK', 'Amsterdam', '85-88238599', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Pattlel', '123 Main St', 6, '3584 PU', 'Tilburg', '82-94511199', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ruby', 'Ansell', '789 Oak Ln', 171, '6982 ZH', 'Utrecht', '80-48515002', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Adeline', 'Wickerson', '789 Oak Ln', 63, '1478 NL', 'Rotterdam', '08-58634392', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Boller', '456 Elm Ave', 239, '0038 FS', 'Amsterdam', '45-85300723', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Camila', 'Nitto', '456 Elm Ave', 194, '9356 YW', 'Breda', '13-88661398', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Ropkes', '123 Main St', 80, '0119 AJ', 'Nijmegen', '62-24755771', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hailey', 'Gannan', '456 Elm Ave', 124, '2051 XU', 'Tilburg', '68-47852022', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Rainford', '123 Main St', 148, '1350 ET', 'Eindhoven', '22-14166717', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Gerlts', '789 Oak Ln', 215, '7758 IO', 'Rotterdam', '72-82665470', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Ellerton', '456 Elm Ave', 242, '1054 JW', 'Tilburg', '14-52181262', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Willow', 'Edland', '456 Elm Ave', 250, '9527 NA', 'Nijmegen', '77-98916109', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Yanshonok', '123 Main St', 80, '6798 QY', 'Almere', '35-66688544', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Luna', 'Probbing', '456 Elm Ave', 145, '8859 UP', 'Rotterdam', '35-64571014', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Giggs', '789 Oak Ln', 235, '7046 WX', 'Nijmegen', '45-59530691', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Rowson', '456 Elm Ave', 58, '7954 AJ', 'Den Haag', '12-07333396', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Danes', '789 Oak Ln', 186, '3050 LH', 'Breda', '03-61880931', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Nora', 'Klyn', '123 Main St', 123, '8208 KR', 'Eindhoven', '08-06093174', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Quinn', 'Beckford', '789 Oak Ln', 39, '0522 QN', 'Almere', '33-82070536', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'McGawn', '456 Elm Ave', 153, '9654 WA', 'Den Haag', '77-13896888', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'de Amaya', '456 Elm Ave', 82, '4371 AY', 'Groningen', '27-34056533', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Crees', '456 Elm Ave', 69, '5068 UX', 'Breda', '90-99519481', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Stiffkins', '456 Elm Ave', 199, '8193 YJ', 'Amsterdam', '02-43890905', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sophia', 'Mantrip', '123 Main St', 172, '2015 EY', 'Nijmegen', '18-54145157', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aurora', 'Isoldi', '123 Main St', 244, '4568 BL', 'Den Haag', '97-27657929', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Levane', '456 Elm Ave', 113, '4879 FW', 'Breda', '67-17554632', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Addison', 'Salterne', '789 Oak Ln', 83, '5886 EL', 'Utrecht', '45-75486685', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Isabella', 'Spatig', '456 Elm Ave', 208, '7434 WF', 'Utrecht', '41-07250667', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'McPharlain', '789 Oak Ln', 240, '2825 ZF', 'Amsterdam', '71-48768171', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Careswell', '456 Elm Ave', 12, '7021 MY', 'Groningen', '16-39558839', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Upcraft', '123 Main St', 160, '9414 CU', 'Amsterdam', '86-87302637', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Genesis', 'Francklin', '789 Oak Ln', 209, '0680 MP', 'Utrecht', '53-56732410', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Poulglais', '789 Oak Ln', 27, '5011 QI', 'Eindhoven', '72-36225766', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Julia', 'Taylo', '789 Oak Ln', 189, '3202 CR', 'Almere', '24-64893223', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Hazel', 'Comiam', '789 Oak Ln', 161, '6307 HP', 'Breda', '50-66586987', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Woolvett', '789 Oak Ln', 187, '4626 SR', 'Almere', '31-29384796', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Langston', '123 Main St', 215, '6090 BQ', 'Groningen', '50-39580237', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Barbie', '123 Main St', 100, '3388 DJ', 'Groningen', '43-90884733', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Deeks', '456 Elm Ave', 1, '9524 BE', 'Breda', '29-64040926', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Scarlett', 'Medhurst', '789 Oak Ln', 89, '7446 AC', 'Tilburg', '37-38471353', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'Subhan', '789 Oak Ln', 3, '7975 GB', 'Nijmegen', '61-16760674', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Satterley', '456 Elm Ave', 243, '4358 FW', 'Nijmegen', '29-47925942', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Caroline', 'Wardell', '789 Oak Ln', 252, '6677 WQ', 'Tilburg', '26-11073627', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Chell', '456 Elm Ave', 146, '9552 WO', 'Groningen', '35-78247101', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Maya', 'Bram', '123 Main St', 110, '4590 BL', 'Eindhoven', '06-78440337', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Teale', '789 Oak Ln', 156, '9231 VF', 'Rotterdam', '24-90254647', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Addison', 'Kelcher', '789 Oak Ln', 251, '6232 NG', 'Almere', '01-97666174', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Dugdale', '789 Oak Ln', 198, '2932 RO', 'Eindhoven', '59-83388714', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Van der Spohr', '789 Oak Ln', 247, '3831 DT', 'Groningen', '48-22213898', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Elizabeth', 'Portal', '456 Elm Ave', 114, '2026 BN', 'Breda', '75-73874121', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Charlotte', 'Heinert', '456 Elm Ave', 77, '6317 TY', 'Rotterdam', '83-89393583', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Gratrex', '789 Oak Ln', 182, '3689 FO', 'Groningen', '44-76540928', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Everly', 'Jenk', '123 Main St', 155, '8792 OI', 'Breda', '73-14588508', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Aria', 'Chew', '789 Oak Ln', 116, '1751 OG', 'Amsterdam', '51-64661909', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sofia', 'Pavelin', '789 Oak Ln', 216, '5062 SX', 'Breda', '45-78273402', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Skurm', '789 Oak Ln', 228, '4666 TT', 'Nijmegen', '39-00257502', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Skylar', 'Nesterov', '123 Main St', 245, '0966 GN', 'Rotterdam', '38-01642297', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Naomi', 'Custance', '789 Oak Ln', 90, '8391 PG', 'Amsterdam', '74-02397657', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Autumn', 'Ivakin', '456 Elm Ave', 236, '0807 TF', 'Almere', '68-90313451', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoey', 'Tremeer', '789 Oak Ln', 214, '6104 WD', 'Rotterdam', '58-86116261', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Stonehewer', '123 Main St', 48, '3607 ZJ', 'Den Haag', '39-73896240', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Chelam', '123 Main St', 171, '3335 OK', 'Nijmegen', '96-07312273', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Veysey', '789 Oak Ln', 205, '7191 QP', 'Groningen', '07-95335336', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Meedendorpe', '456 Elm Ave', 240, '8343 HT', 'Amsterdam', '76-14000485', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lydia', 'Lilie', '123 Main St', 69, '6728 BY', 'Groningen', '12-74866056', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Anna', 'Tims', '456 Elm Ave', 45, '0298 RI', 'Groningen', '00-44020579', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Alexa', 'McGeraghty', '123 Main St', 142, '1140 KW', 'Utrecht', '34-90722277', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ariana', 'Hodgin', '456 Elm Ave', 198, '6568 VN', 'Utrecht', '14-63607061', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Gorriessen', '123 Main St', 173, '3709 CY', 'Amsterdam', '15-99491368', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'Bilsford', '789 Oak Ln', 95, '2832 KP', 'Rotterdam', '32-59379551', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Stanyan', '789 Oak Ln', 137, '8530 YY', 'Nijmegen', '48-17166909', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eleanor', 'Gillbe', '789 Oak Ln', 159, '9620 OT', 'Rotterdam', '41-83970235', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Sempill', '789 Oak Ln', 165, '1244 CK', 'Breda', '97-82021658', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lily', 'Josefsohn', '123 Main St', 9, '5401 EE', 'Groningen', '17-16676775', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Kennedy', 'Ballintime', '456 Elm Ave', 154, '7166 BC', 'Den Haag', '59-39165570', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Violet', 'Wharin', '123 Main St', 31, '8578 CT', 'Tilburg', '27-29557304', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Martini', '789 Oak Ln', 224, '6849 JW', 'Groningen', '90-92028077', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Lucy', 'Bonsale', '789 Oak Ln', 63, '5726 XG', 'Tilburg', '61-90399013', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Josephine', 'Dudding', '456 Elm Ave', 52, '9845 MX', 'Tilburg', '62-05647584', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ellie', 'Mole', '789 Oak Ln', 221, '0084 CQ', 'Nijmegen', '25-68120273', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Eva', 'Smorthit', '789 Oak Ln', 91, '5779 BV', 'Nijmegen', '28-44676965', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Victoria', 'Giacobini', '789 Oak Ln', 131, '0872 EZ', 'Almere', '99-59444969', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gabriella', 'O'' Hern', '789 Oak Ln', 74, '0271 QS', 'Rotterdam', '31-53333369', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Sloat', '456 Elm Ave', 7, '6974 AM', 'Eindhoven', '54-31340792', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Merington', '456 Elm Ave', 183, '9009 XF', 'Almere', '06-68104390', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Chloe', 'Jay', '456 Elm Ave', 126, '2440 IG', 'Nijmegen', '36-10403503', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emery', 'Eallis', '123 Main St', 143, '5582 AM', 'Nijmegen', '35-70673112', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'Tschersich', '123 Main St', 64, '2238 DP', 'Groningen', '61-72115847', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'Duckitt', '456 Elm Ave', 154, '6918 VW', 'Utrecht', '64-07212344', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Smeaton', '456 Elm Ave', 49, '8669 KA', 'Breda', '10-47875852', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sarah', 'Budik', '456 Elm Ave', 110, '4078 OF', 'Tilburg', '70-08363042', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Julia', 'Mawtus', '789 Oak Ln', 181, '4442 LQ', 'Groningen', '42-14630653', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Noah', 'Moseley', '456 Elm Ave', 254, '8270 OW', 'Breda', '04-14003930', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Catteroll', '456 Elm Ave', 20, '2502 OR', 'Nijmegen', '82-26211807', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Olivia', 'Jakoubek', '456 Elm Ave', 45, '2841 EZ', 'Rotterdam', '37-05603489', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Goodfield', '789 Oak Ln', 124, '3676 KN', 'Den Haag', '10-28055099', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Layla', 'Catmull', '456 Elm Ave', 4, '0025 XD', 'Breda', '74-28393465', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Grace', 'Trayton', '789 Oak Ln', 38, '9764 KO', 'Nijmegen', '19-54189756', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Liam', 'Tomaszkiewicz', '456 Elm Ave', 62, '3180 YN', 'Groningen', '86-79221315', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Claire', 'Quiddihy', '123 Main St', 41, '1157 CS', 'Amsterdam', '78-39169758', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Emma', 'Annand', '456 Elm Ave', 181, '2537 JQ', 'Almere', '94-92293228', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ivy', 'Hymas', '123 Main St', 247, '1644 YU', 'Rotterdam', '75-44460590', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Gianna', 'MacCartair', '123 Main St', 240, '3039 PG', 'Almere', '94-89093160', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Abigail', 'Harrie', '456 Elm Ave', 209, '7621 HF', 'Rotterdam', '70-11046085', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Natalie', 'Davion', '123 Main St', 204, '4053 GI', 'Breda', '49-97033988', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'Davidovich', '123 Main St', 96, '0342 GB', 'Rotterdam', '95-80927116', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Savannah', 'Ridd', '123 Main St', 184, '9524 AI', 'Nijmegen', '40-39878238', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Cora', 'Fussen', '789 Oak Ln', 133, '1983 KX', 'Amsterdam', '22-40404739', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Bella', 'Luxton', '789 Oak Ln', 164, '8881 RB', 'Almere', '08-29993070', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Allison', 'Leathlay', '456 Elm Ave', 121, '0233 PA', 'Utrecht', '61-62466784', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Ava', 'Kennermann', '456 Elm Ave', 254, '7419 RJ', 'Den Haag', '17-96640094', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Brooklyn', 'Ferson', '789 Oak Ln', 186, '8436 KM', 'Breda', '80-20105907', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Stella', 'Achrameev', '123 Main St', 138, '8990 DU', 'Den Haag', '83-09642296', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Leah', 'Cleworth', '123 Main St', 153, '6164 RN', 'Breda', '44-44793759', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Sadie', 'MacAirt', '456 Elm Ave', 118, '1624 JZ', 'Utrecht', '24-27847044', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Avery', 'Wessel', '123 Main St', 50, '3978 WL', 'Groningen', '43-03747096', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Serenity', 'Veal', '789 Oak Ln', 68, '0304 QI', 'Amsterdam', '55-60476989', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Valentina', 'McLice', '123 Main St', 4, '0018 KQ', 'Den Haag', '33-92955460', true);
insert into patienten (first_name, last_name, address, house_number, postcode, city, phone_number, active) values ('Zoe', 'Siehard', '789 Oak Ln', 88, '3447 GR', 'Utrecht', '56-58414174', true);
